# -*- coding: utf-8 -*-
"""複合動詞　分散表現　 のコピー

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I22d0ounCoE_geaTzixYe4cIHGiHE2ty
"""

# ==========================================
# Step 1: ライブラリのダウンロード
# ==========================================
!pip install -q gensim scikit-learn
!pip install -q sudachipy
!pip install -q sudachidict_core
!pip install -q japanize-matplotlib seaborn

# ==========================================
# Step 2: chiVeモデルのダウンロードと展開
# ==========================================
import os
import glob
import gensim
import sudachipy
from sudachipy import dictionary, tokenizer
from collections import Counter
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

def load_chive_model():
    """ChiVeモデルをダウンロードし、ロードして返す"""
    # ダウンロード確認
    if not os.path.exists("chive-1.3-mc90_gensim.tar.gz"):
        print("[System] ChiVeモデルをダウンロードしています...")
        !wget https://sudachi.s3-ap-northeast-1.amazonaws.com/chive/chive-1.3-mc90_gensim.tar.gz
        !tar -zxvf chive-1.3-mc90_gensim.tar.gz
    else:
        print("[System] ChiVeモデルは既に存在します。")

    # パス特定
    kv_files = glob.glob("**/*.kv", recursive=True)
    if not kv_files:
        raise FileNotFoundError("エラー: モデルファイル(.kv)が見つかりません。")

    print(f"[System] モデルをロード中: {kv_files[0]} ...")
    model = gensim.models.KeyedVectors.load(kv_files[0])
    print("[System] モデルロード完了。")
    return model

# グローバル変数としてモデルを保持（後続の関数で使うため）
word_vectors = load_chive_model()

# ==============================================================================
# Step 3: sudachiで形態素解析エンジン
# 機能: テキストから複合動詞(V1+V2)を抽出し、表記・原形を整理する
# ==============================================================================
def extract_compound_verbs(text):
    """
    テキストから「動詞+動詞」の連鎖を抽出する
    Returns: List of dict [{'v1_surf':..., 'v1_base':..., 'v2_base':..., 'comp_key':...}]
    """
    tokenizer_obj = dictionary.Dictionary().create(mode=tokenizer.Tokenizer.SplitMode.A)
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    extracted_data = []

    print("[Analysis] テキスト解析を実行中...")
    for line in lines:
        morphemes = tokenizer_obj.tokenize(line)
        # 扱いやすいように辞書リストに変換
        tokens = [{
            "surface": m.surface(),
            "lemma": m.normalized_form(),
            "pos": m.part_of_speech()
        } for m in morphemes]

        for i in range(len(tokens) - 1):
            v1 = tokens[i]
            v2 = tokens[i+1]

            # 動詞判定ロジック (一般動詞または非自立動詞)
            def is_verb(t):
                return t["pos"][0] == "動詞" and t["pos"][1] in ["一般", "非自立可能"]

            if is_verb(v1) and is_verb(v2):
                # ★分析の鍵: 検索キーと統計用キーを分離
                # 複合動詞キー: 「読み(表記)」+「始める(原形)」= "読み始める" (ベクトル検索用)
                # 統計用キー: 「読む(原形)」+「始める(原形)」 (頻度集計・対応分析用)
                if v1["lemma"] == v2["lemma"]:
                    continue

                extracted_data.append({
                    "v1_surface": v1["surface"],
                    "v1_lemma": v1["lemma"],
                    "v2_lemma": v2["lemma"],
                    "comp_key": v1["surface"] + v2["lemma"]
                })
    return extracted_data

# ==============================================================================
# Step 4: 統計解析エンジン (頻度・ΔP・log-r)
# 機能: 共起頻度、周辺頻度、双方向のΔP、共起強度を計算する
# ==============================================================================
def calculate_statistics(extracted_data):
    """データリストから頻度表とΔPスコアを含むDataFrameを作成する"""
    if not extracted_data:
        return pd.DataFrame()

    total_n = len(extracted_data)

    # ペアのカウント (キー: v1原形, v2原形)
    pair_counts = Counter([(d["v1_lemma"], d["v2_lemma"]) for d in extracted_data])
    v1_total = Counter([d["v1_lemma"] for d in extracted_data])
    v2_total = Counter([d["v2_lemma"] for d in extracted_data])

    # 複合動詞キーの代表選定 (最も頻度の高い表記を採用)
    # 例: ("読む", "始める") に対して "読み始める" を割り当てる
    key_map = {}
    key_counts = Counter([(d["v1_lemma"], d["v2_lemma"], d["comp_key"]) for d in extracted_data])
    for (v1, v2, k), _ in key_counts.most_common():
        if (v1, v2) not in key_map:
            key_map[(v1, v2)] = k

    stats_rows = []
    print("[Stats] 計算中...")

    for (v1, v2), a in pair_counts.most_common():
        # a: 共起頻度
        # b: V1あり・V2なし
        b = v1_total[v1] - a
        # c: V1なし・V2あり
        c = v2_total[v2] - a
        # d: V1なし・V2なし
        d = total_n - (a + b + c)

        stats_rows.append({
            "V1_原形": v1,
            "V2_原形": v2,
            "複合動詞_Key": key_map[(v1, v2)],
            "頻度(Pair)": a,
            "頻度(V1_Total)": v1_total[v1],
            "頻度(V2_Total)": v2_total[v2],
        })

    return pd.DataFrame(stats_rows)

# ==============================================================================
# Step 5: ベクトル解析エンジン (意味的距離・構成性)
# 機能: V1, V2, V1+V2 それぞれと複合動詞とのコサイン類似度を計算
# ==============================================================================
def calculate_vectors(row, model):
    """DataFrameの1行に対してベクトル演算を行う関数"""
    v1 = row['V1_原形']
    v2 = row['V2_原形']
    comp = row['複合動詞_Key']

    # 辞書チェック
    if v1 not in model or v2 not in model or comp not in model:
        return pd.Series([None, None, None])

    vec_v1 = model[v1]
    vec_v2 = model[v2]
    vec_comp = model[comp]
    vec_add = vec_v1 + vec_v2 # 加法構成性

    # 類似度計算 (reshapeはエラー回避用)
    sim_v1 = cosine_similarity(vec_comp.reshape(1, -1), vec_v1.reshape(1, -1))[0][0]
    sim_v2 = cosine_similarity(vec_comp.reshape(1, -1), vec_v2.reshape(1, -1))[0][0]
    sim_add = cosine_similarity(vec_comp.reshape(1, -1), vec_add.reshape(1, -1))[0][0]

    return pd.Series([sim_v1, sim_v2, sim_add])

# ==============================================================================
# Step 6: メイン実行パイプライン
# 機能: ファイル読み込み -> 各エンジンの実行 -> CSV出力 -> ダウンロード
# ==============================================================================
def main_pipeline(file_path):
    # 1. ファイル読み込み
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            text = f.read()
        print(f"[Input] ファイル読み込み完了: {len(text)}文字")
    else:
        print("[Input] 指定ファイルなし。ダミーデータを使用します。")
        text = "私は本を読み始める。彼は落ち着く。計画を取り消す。思い切る。走り続ける。"

    # 2. 形態素解析
    extracted = extract_compound_verbs(text)
    if not extracted:
        print("エラー: 動詞ペアが見つかりませんでした。")
        return

    # 3. 統計計算
    df = calculate_statistics(extracted)

    # 4. ベクトル計算
    print("[Vector] コサイン類似度を計算中...")
    vec_cols = ["Sim(Comp-V1)", "Sim(Comp-V2)", "Sim(Comp-Add)"]
    df[vec_cols] = df.apply(lambda row: calculate_vectors(row, word_vectors), axis=1)

    # 5. 結果の整理と出力
    # 可視化・対応分析に使いやすいようにカラム順を整理
    output_cols = [
        "V1_原形", "V2_原形", "複合動詞_Key",
        "頻度(Pair)", "頻度(V1_Total)", "頻度(V2_Total)",
        "Sim(Comp-V1)", "Sim(Comp-V2)", "Sim(Comp-Add)"
    ]
    df_final = df[output_cols].round(4) # 小数点4桁で丸める

    output_filename = "BCCWJ_compound_verb_analysis_data.csv"
    df_final.to_csv(output_filename, index=False, encoding="utf-8-sig")

    print("\n" + "="*60)
    print(f"【分析完了】 ファイルを作成しました: {output_filename}")
    print(f"データ件数: {len(df_final)}件")
    print("="*60)
    print(df_final.head())

    files.download(output_filename)

# --- 実行 ---
# ファイルパスを指定して実行
target_file = '/content/drive/MyDrive/bccwj.txt'
main_pipeline(target_file)